[rocks]

[plugins]
"rocks.nvim" = "2.32.0"
"rocks-treesitter.nvim" = "scm"
"rocks-git.nvim" = "1.5.1"
"rocks-config.nvim" = "2.1.1"
"rocks-lazy.nvim" = "scm"
nvim-lspconfig = "0.1.8"
"schemastore.nvim" = "0.2.0"
luasnip = "2.3.0"
cmp-nvim-lsp = "scm"
cmp-buffer = "scm"
cmp-path = "scm"
cmp-cmdline = "scm"
cmp-git = "scm"
"plenary.nvim" = "scm"
neogit = "1.0.0"
"diffview.nvim" = "scm"
"fidget.nvim" = "1.4.1"
"rainbow-delimiters.nvim" = "0.4.0"
nvim-autopairs = "scm"
"indent-blankline.nvim" = "3.7.0"
nvim-cmp = "0.0.1"
"which-key.nvim" = "2.1.0"

[plugins.auto-session]
version = "2.1.0"

[plugin.auto-session.config]
auto_session_create_enabled = true
auto_save_enabled = true
auto_restore_enabled = true

[plugin.nvim-ts-autotag]
version = "scm"
config.opts.enable_close_on_slash = true

[plugins."conform.nvim"]
version = "6.0.0"
config = "configs.formatters"

[plugins.nvim-lint]
version = "scm"
config = "configs.linters"

[plugins.nvim-lightbulb]
version = "1.0.0"
config.autocmd.enabled = true

[plugins.cmp-luasnip]
git = "github:saadparwaiz1/cmp_luasnip"

[plugins.cmp-dotenv]
git = "github:SergioRibera/cmp-dotenv"

[plugins."gitsigns.nvim"]
git = "github:lewis6991/gitsigns.nvim"
rev = "v0.9.0"

[plugins."garbage-day.nvim"]
git = "github:zeioth/garbage-day.nvim"
rev = "v1.3.0"

[plugins.nvim-puppeteer]
git = "github:chrisgrieser/nvim-puppeteer"

[plugins."coerce.nvim"]
git = "github:gregorias/coerce.nvim"
rev = "v2.1"

[plugins."grug-far.nvim"]
git = "github:MagicDuck/grug-far.nvim"
config = "configs.search"

[treesitter]
snippet_engine = "luasnip"
auto_install = true
sync_install = true
highlight.enable = true
incremental_selection.enable = true
indent.enable = true

[bundles.editing]
items = [
  "indent-blankline.nvim",
  "rainbow-delimiters.nvim",
  "nvim-autopairs",
  "nvim-puppeteer",
  "coerce.nvim",
]
config = "configs.editing"

[bundles.git]
items = ["gitsigns.nvim", "neogit", "diffview.nvim"]
config = 'configs.git'

[bundles.lsp]
items = [
  "nvim-lspconfig",
  "nvim-lightbulb",
  "schemastore.nvim",
  "cmp-nvim-lsp",
  "garbage-day.nvim",
  "fidget.nvim",
]
config = "configs.lsp"

[bundles.completion]
items = [
  "luasnip",
  "nvim-cmp",
  "cmp-nvim-lsp",
  "cmp-buffer",
  "cmp-path",
  "cmp-cmdline",
  "cmp-luasnip",
  "cmp-dotenv",
]
config = "configs.cmp"
