[rocks]

[plugins]
"rocks.nvim" = "2.31.3"
"rocks-treesitter.nvim" = "scm"
"rocks-git.nvim" = "1.5.1"
"rocks-config.nvim" = "2.0.0"
"rocks-lazy.nvim" = "scm"
nvim-lspconfig = "0.1.8"
"schemastore.nvim" = "0.2.0"
cmp-nvim-lsp = "scm"

[plugins.nvim-lightbulb]
version = "1.0.0"
config.autocmd.enabled = true

[treesitter]
auto_install = true
sync_install = true
highlight.enable = true
incremental_selection.enable = true
indent.enable = true

[bundles.lsp]
items = [
  "nvim-lspconfig",
  "nvim-lightbulb",
  "schemastore.nvim",
  "cmp-nvim-lsp",
]
config = "configs.lsp"
